name: sherlock
channels:
 - conda-forge
 - defaults
dependencies:
  - numpy=1.23.5
  - matplotlib=3.5.2
  - pandas=1.5.3
  - astropy=5.0.4
  - scipy=1.8.0
  - python=3.10
  - jupyterlab
  - gfortran_linux-64
  - gcc_linux-64
  - pip
  - pip:
    - alexfitter==1.2.12
    - arviz==0.12.1
    - astroplan==0.8
    - astropy==5.0.4
    - astropy-healpix==0.7
    - astroquery==0.4.6
    - autograd==1.5
    - batman-package==2.4.9
    - beautifulsoup4==4.9.3
    - blosc2==2.0.0
    - bokeh==2.4.2
    - celerite==0.4.0
    - certifi==2023.5.7
    - cffi==1.15.1
    - cftime==1.6.2
    - chardet==4.0.0
    - cmake==3.26.3
    - configparser==5.0.1
    - corner==2.2.2
    - cryptography==41.0.0
    - cycler==0.11.0
    - Cython==0.29.21
    - dearwatson==0.7.6
    - Deprecated==1.2.14
    - dynesty==1.0.1
    - ellc==1.8.5
    - emcee==3.0.2
    - everest-pipeline==2.0.12
    - extension-helpers==0.1
    - fbpca==1.0
    - filelock==3.12.0
    - foldedleastsquares==1.0.42
    - fonttools==4.39.4
    - future==0.18.3
    - george==0.4.0
    - html5lib==1.1
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==6.6.0
    - jaraco.classes==3.2.3
    - jeepney==0.8.0
    - Jinja2==3.1.2
    - joblib==1.2.0
    - k2plr==0.2.9
    - keyring==23.13.1
    - kiwisolver==1.4.4
    - lcbuilder==0.12.3
    - lightkurve==2.4.0
    - lit==16.0.5
    - llvmlite==0.40.0
    - lxml==4.9.2
    - MarkupSafe==2.1.2
    - matplotlib==3.5.2
    - MechanicalSoup==1.2.0
    - memoization==0.4.0
    - mock==4.0.3
    - more-itertools==9.1.0
    - mpmath==1.3.0
    - msgpack==1.0.5
    - multipledispatch==0.6.0
    - netCDF4==1.6.3
    - networkx==3.1
    - numba==0.57.0
    - numexpr==2.8.4
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oktopus==0.1.2
    - packaging==23.1
    - pandas==1.5.3
    - patsy==0.5.3
    - pdf2image==1.16.2
    - photutils==1.0.2
    - Pillow==9.5.0
    - pip==23.1.2
    - py-cpuinfo==9.0.0
    - pybind11==2.10.4
    - pycparser==2.21
    - pyerfa==2.0.0.3
    - pyparsing==2.4.7
    - PyPDF2==3.0.1
    - pyrr==0.10.3
    - pysyzygy==0.0.2
    - python-dateutil==2.8.2
    - PyTransit==2.5.21
    - pytz==2023.3
    - pyvo==1.4.1
    - PyYAML==5.4.1
    - rebound==3.17.3
    - reportlab==3.5.59
    - reproject==0.4
    - requests==2.25.1
    - scikit-learn==1.2.2
    - scipy==1.8.0
    - seaborn==0.11.1
    - SecretStorage==3.3.3
    - semantic-version==2.10.0
    - setuptools==58.1.0
    - sherlockpipe==0.36.8
    - six==1.16.0
    - sklearn==0.0
    - soupsieve==2.4.1
    - statsmodels==0.13.5
    - sympy==1.12
    - tables==3.8.0
    - tess-point==0.6.1
    - threadpoolctl==3.1.0
    - timezonefinder==5.2.0
    - torch==2.0.0
    - tornado==6.3.2
    - tqdm==4.56.0
    - triceratops==1.0.17
    - triton==2.0.0
    - typing_extensions==4.3.0
    - uncertainties==3.1.5
    - urllib3==1.26.13
    - webencodings==0.5.1
    - wheel==0.40.0
    - wotan==1.9
    - wrapt==1.15.0
    - xarray==2023.5.0
    - xarray-einstats==0.5.1
    - zipp==3.15.0
