name: sherlock
channel_priority: strict
channels:
 - conda-forge
 - defaults
dependencies:
  - numpy=1.23.5
  - cython=0.29.35
  - python=3.10
  - jupyterlab=4.0.2
  - gfortran_linux-64=13.1.0
  - gcc_linux-64=13.1.0
  - matplotlib=3.5.2
  - pandas=1.5.3
  - astropy=5.0.4
  - scipy=1.8.0
  - pip=23.1.2
  - pip:
    - lightkurve==2.4.0
    - wotan==1.9
    - foldedleastsquares==1.0.42
